=== RegioneUmbria-RCB/VBG/src/java/VBG-CNSHANDLER/WebContent/WEB-INF/smartcardprofiles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.progettopeople.it/sirac/peoplesmartcardprofiles"
	xmlns:scp="http://www.progettopeople.it/sirac/peoplesmartcardprofiles"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<complexType name="CertDistinguishedNamePattern">
		<simpleContent>
			<extension base="string">
				<attribute name="tokenSeparator" type="string"
					use="required">
				</attribute>
				<attribute name="datePattern" type="string"
					default="mmDDyyyy">
				</attribute>
			</extension>
		</simpleContent>
	</complexType>
	<simpleType name="CardDescription">
		<restriction base="string">
			<maxLength value="300"></maxLength>
			<whiteSpace value="preserve"></whiteSpace>
			<minLength value="0"></minLength>
		</restriction>
	</simpleType>
	<simpleType name="CertificateIssuer">
		<restriction base="string">
			<maxLength value="300"></maxLength>
			<whiteSpace value="preserve"></whiteSpace>
			<minLength value="0"></minLength>
		</restriction>
	</simpleType>
	<simpleType name="CardATR">
		<restriction base="string">
			<maxLength value="100"></maxLength>
			<whiteSpace value="preserve"></whiteSpace>
			<minLength value="0"></minLength>
		</restriction>
	</simpleType>
	
	<complexType name="CertificateValidityCheck">
		<attribute name="enabled" type="boolean" use="required"></attribute>
	</complexType>
	<complexType name="CertificateChainCheck">
		<attribute name="enabled" type="boolean" use="required"></attribute>
	</complexType>
	<complexType name="CRLCheck">
        <sequence minOccurs="0" maxOccurs="unbounded">
			<element name="alternativeCRLDistributionPointURL" type="scp:AlternativeCRLDistributionPointURL" minOccurs="1" maxOccurs="1"></element>
		</sequence>
		<attribute name="enabled" type="boolean" use="required"></attribute>
		<attribute name="onCardCrlURLCheck" type="boolean"
			use="required">
		</attribute>
		<attribute name="overrideInternalCRLUpdateInterval" type="boolean" use="required"></attribute>
		<attribute name="updateIntervalHours" type="positiveInteger" use="required"></attribute>
		<attribute name="crlFileName" type="string" use="required">
			<annotation>
				<documentation>pippo!</documentation>
			</annotation>
		</attribute>
	</complexType>

	<element name="SmartCardProfiles" type="scp:SmartCardProfiles"></element>

	<complexType name="SmartCardProfiles">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="SmartCardProfile"
				type="scp:SmartCardProfile" minOccurs="1" maxOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="SmartCardProfile">
		<sequence minOccurs="1" maxOccurs="1">
		<element name="CardDescription" type="scp:CardDescription" minOccurs="1" maxOccurs="1"></element>
		<element name="CardATR" type="scp:CardATR" minOccurs="1" maxOccurs="1"></element>
		<element name="CardLibraries" type="scp:CardLibraries" minOccurs="1" maxOccurs="1">
			</element>
		<element name="CertificateIssuer" type="scp:CertificateIssuer" minOccurs="1" maxOccurs="1"></element>
		<element name="CertificateValidityCheck" type="scp:CertificateValidityCheck" minOccurs="1" maxOccurs="1"></element>
		<element name="CertificateChainCheck" type="scp:CertificateChainCheck" minOccurs="1" maxOccurs="1"></element>
		<element name="CRLCheck" type="scp:CRLCheck" minOccurs="1" maxOccurs="1"></element>
		<element name="DistinguishedNamePattern"
			type="scp:CertDistinguishedNamePattern" minOccurs="1"
			maxOccurs="1">
		</element>
		</sequence>
		<attribute name="cardType" type="scp:CardTypeRestriction"
			use="required">
		</attribute>
	</complexType>

	<simpleType name="CardLibraryTypeRestriction">
		<restriction base="NMTOKEN">
			<enumeration value="csp" />
			<enumeration value="pkcs11" />
		</restriction>
	</simpleType>

	<complexType name="CardLibraries">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="CardLibrary" type="scp:CardLibrary"></element>
		</sequence>
	</complexType>

	<complexType name="CardLibrary">
		<simpleContent>
			<extension base="string">
				<attribute name="type"
					type="scp:CardLibraryTypeRestriction" use="required">
				</attribute>
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="AlternativeCRLDistributionPointURL">
		<restriction base="string"></restriction>
	</simpleType>

	<simpleType name="CardTypeRestriction">
		<restriction base="NMTOKEN"></restriction>
	</simpleType>

</schema>

=== RegioneUmbria-RCB/VBG/src/java/VBG-CNSHANDLER/WebContent/WEB-INF/smartcard_profiles.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<SmartCardProfiles xmlns="http://www.progettopeople.it/sirac/peoplesmartcardprofiles" xmlns:scp="http://www.progettopeople.it/sirac/peoplesmartcardprofiles"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.progettopeople.it/sirac/peoplesmartcardprofiles smartcardprofiles.xsd">

	<!-- POSTECOM -->

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Incrypto34v2</CardDescription>
		<CardATR>3bff1800ff8131fe55006b0209020001010144534410318092</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="true" updateIntervalHours="10" crlFileName="PostecomIncrypto.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl0</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[OID.2.5.4.13="C=$Cognome$/N=$Nome$/D=$DataDiNascita$/R=TITOLARE", EMAILADDRESS=$Email$, CN=$Cognome$/$Nome$/$CodiceFiscale$/$CodiceCarta$, OU=Titolari, L=RA1, O=Utente Postecert, C=IT]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>


	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Gemplus</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">gclib.dll</CardLibrary>
			<CardLibrary type="csp">gemcsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10" crlFileName="PostecomGemplus.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl0</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[OID.2.5.4.13="C=$Cognome$/N=$Nome$/D=$DataDiNascita$/R=TITOLARE", EMAILADDRESS=$Email$, CN=$Cognome$/$Nome$/$CodiceFiscale$/$CodiceCarta$, OU=Titolari, L=RA1, O=Postecom s.p.a., C=IT]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>


	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Firma per Titolare - Autenticazione</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl0</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[SURNAME=$Cognome$, GIVENNAME=$Nome$, CN=$Cognome2$/$Nome2$/$CodiceFiscale$/$CodiceCarta$, O=NON PRESENTE, C=IT]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>


	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Firma per Titolare 2 - Autenticazione</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare2.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl3</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[SURNAME=$Cognome$, GIVENNAME=$Nome$, CN=$Cognome2$/$Nome2$/$CodiceFiscale$/$CodiceCarta$, O=POSTECOM SPA/05838841004, C=IT]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Firma per Titolare 3 - Autenticazione</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare3.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl3</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[SURNAME=$Cognome$, GIVENNAME=$Nome$, CN=$Cognome2$/$Nome2$/$CodiceFiscale$/$CodiceCarta$, OU=$OrganizationUnit$ O=$Organization$, C=$Country$]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Firma per Titolare - Firma digitale</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl0</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[DNQ=$Dnq$, SURNAME=$Cognome$, GIVENNAME=$Nome$, SERIALNUMBER=IT:$CodiceFiscale$, CN=$CognomeNome$, O=$Organization$, C=$CountryCode$]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom Gemplus 2</CardDescription>
		<CardATR>3be200ffc11031fe55c8029c</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">gclib.dll</CardLibrary>
			<CardLibrary type="csp">gemcsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA1</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10" crlFileName="PostecomGemplus.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca1/crl3</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[SURNAME=$Cognome$, GIVENNAME=$Nome$, CN=$Cognome$/$Nome$/$CodiceFiscale$/$CodiceCarta$, O=$Organization$, C=IT]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom - Touch and Sign con chiavi DS a 2048 bits</CardDescription>
		<CardATR>3bff1800ff8131fe55006b0209030301010144534410318090</CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA2</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca2/crl0.crl</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[T=$Titolo$, DNQ=$Dnq$, SURNAME=$Cognome$, GIVENNAME=$Nome$, SERIALNUMBER=IT:$CodiceFiscale$, CN=$CognomeNome$, O=$Organization$, C=$CountryCode$]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom - Touch and Sign con chiavi DS a 2048 bits</CardDescription>
		<CardATR></CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
			<CardLibrary type="csp">sysgillocsp.dll</CardLibrary>
		</CardLibraries>
		<CertificateIssuer>Postecom CA2</CertificateIssuer>
		<CertificateValidityCheck enabled="true" />
		<CertificateChainCheck enabled="true" />
		<CRLCheck enabled="false" onCardCrlURLCheck="true" overrideInternalCRLUpdateInterval="false" updateIntervalHours="10"
			crlFileName="PostecomFirmaTitolare.crl">
			<alternativeCRLDistributionPointURL>http://postecert.poste.it/postecomca2/crl0.crl</alternativeCRLDistributionPointURL>
		</CRLCheck>
		<DistinguishedNamePattern tokenSeparator="$" datePattern="dd/MM/yyyy">
			<![CDATA[DNQ=$Dnq$, SURNAME=$Cognome$, GIVENNAME=$Nome$, SERIALNUMBER=IT:$CodiceFiscale$, CN=$CognomeNome$, OU=$OrganizationUnit$, O=$Organization$, C=$CountryCode$]]>
		</DistinguishedNamePattern>
	</SmartCardProfile>

	<SmartCardProfile cardType="Postecom">
		<CardDescription>Postecom - Touch and Sign con chiavi DS a 2048 bits</CardDescription>
		<CardATR></CardATR>
		<CardLibraries>
			<CardLibrary type="pkcs11">incryptoki2.dll</CardLibrary>
